window.SPR=function(){function z(a,d){var c=this;c.H=[];c.w=a||{};c.Bc=b.lc;c.pa=!1;c.dc=d||b.Sb;p.Nb(c.dc);h.a(a[b.qa]);a[b.c]=a[b.c]||q.current[b.c];a[b.url]=a[b.url]||e.ia();a[b.title]||(a[b.title]=e.ha(a[b.url]));if(a[b.url])c.a=function(){if(c.bc())return c.Kb(),c;h[b.error](c.sb());return null},c[b.nc]=function(a){c.cc(a)?c.Lb(a):c.qb(a);return c},c[b.gc]=function(a){c.$b(a)?c.Jb(a):c.pb();return c},c[b.ec]=function(){c.pa||(c.D(c.da(c.da())),c[b.Ea](100),c.pa=!0);return c},c[b.Ea]=function(a){if(f.contains(c.H,
a))return null;if(f.contains(f.T,a)){var d=c.j();d[b.u]=b.Fa;d[b.Fa]=c.Xa(a);c.D(d)}else h[b.error](b.eb);return c},c.Xa=function(a){var d,n=f.T,e={};if(!f.contains(n,a))h[b.error](b.ra);else if(!f.contains(c.H,a))for(d=0;d<n.length;d+=1){var l=n[d];a>=l&&!f.contains(c.H,l)&&(c.H.push(l),e[l]=!0,h[b.info](b.za+l))}return e},c.D=function(a){p.f(b.g,b.ic,a)},c.Kb=function(){c.D(c.bb())},c.Ec=function(){return q.current},c.j=function(){return v.ba(c.w)},c.bb=function(){var a=c.j();a[b.u]=b.kc;return a},
c.bc=function(){var a;for(a=0;a<r.length;a+=1)if(!c.w[r[a]])return!1;return!0},c.sb=function(){var a,d=[];for(a=0;a<r.length;a+=1)c.w[r[a]]||d.push(r[a]);return b.fb+d.join(", ")},c.Lb=function(a){c.D(c.Vb(a))},c.cc=function(a){return a===b.qc||a===b.rc},c.Vb=function(a){var d=c.j();d[b.u]=b.oc;d[b.pc]=a;return d},c.qb=function(a){if(a)h[b.error](a+b.gb);else h[b.error](b.Yb)},c.da=function(){var a=c.j();a[b.u]=b.fc;return a},c.Jb=function(a){c.D(c.Ua(a))},c.Ua=function(a){var d=c.j();d[b.u]=b.hc;
d[b.mc]=a;return d},c.$b=function(a){return!isNaN(a)},c.pb=function(){h[b.error](b.cb)};else h[b.error](b.W+b.ja)}var b={g:"edge.simplereach.com",version:"1",La:"d8rk54i4mohrb.cloudfront.net",ab:"/n",Wb:"/t",ic:"/v",ka:"/event",Ja:"/pixel?bad=true&error=",yc:"/iframe.html",Ma:"/container.html",Aa:"000000000000000000000000",W:"SPR-ERROR: ",ja:"100 - Missing url",Bb:"__reach_config",Ka:"cache_buster",xa:"__srret",Da:"__srui",K:"0",vb:"1",$a:"img",wb:"1px",width:"width",Z:"undefined",error:"error",tb:"off",
info:"info",F:"SPR_DEBUG",Tb:"//",X:"string",referrer:"referrer",uid:"uid",l:"callback",f:"jsonp",url:"url",title:"title",c:"pid",ya:"s",r:"r",t:"t",e:"e",x:"x",n:"n",Zb:"v",qa:"ignore_errors",Ab:"preview",L:"authors",N:"channels",Y:"tags",s:"date",zc:"inframe",xc:"iframe",Oa:"custom_tracking",Cb:"reach_tracking",A:"ref_url",va:"page_url",Jc:"user_id",rb:"manual_scroll_depth",ga:"content_height",Dc:"rd",wc:"fb",sc:"de",mb:"li",xb:"pi",Na:"csd",nb:"www.linkedin.com",yb:"partners-api.pinterest.com",
ob:"/countserv/count/share",zb:"/v1/urls/count.json",ra:"[error] Invalid amount please send scroll depths of only: 25, 50, 75 or 100",za:"[info] sending scrollDepth of: ",Ib:"[info] scroll depth not activated, not sending data",Sb:"SimplereachVideo",u:"event_name",fb:"Missing params please provide a ",gb:" is not a valid start event type.",Yb:"Cannot have an undefined start type. Please provide a start type.",cb:"Please pass a valid number",eb:"[error] Invalid quartile please send quartiles of only: 25, 50, 75 or 100",
Fc:"[error] Quartile for this video already sent",jc:"video_id",lb:"length",description:"description",Ic:"thumbnail_url",Gc:"source_url",ua:"networks",lc:"video",nc:"start",gc:"elapsed",ec:"complete",Ea:"quartile",kc:"init",oc:"start",hc:"elapsed",Fa:"quartile",fc:"complete",pc:"start_type",qc:"auto",rc:"click",mc:"seconds_elapsed"},f={Gb:function(){return Math.random().toString(36).replace(/[^a-z]+/g,"")},returnValue:function(a){return a},R:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===
Object.prototype.toString.call(a)},log:function(a){window.console&&console.log(a)},Ac:function(a){return"[object String]"===Object.prototype.toString.call(a)},J:function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b},ta:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a},contains:function(a,b){return-1!==(a.join(",")+",").indexOf(b+",")},O:function(a){typeof a===b.X&&(a=a.split(","));if(this.R(a)){for(var d=0;d<a.length;d+=1)typeof a[d]===b.X&&(a[d]=a[d].replace(/^\s*/,
"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}},v:function(){},ma:function(){return window.location.protocol+"//"},T:[25,50,75,100]},t={encode:function(a,b){var c=[];if(f.R(a))for(var d=0,g;d<a.length;d+=1)g=a[d],/\[\]$/.test(b)?c.push(encodeURIComponent(b)+"="+encodeURIComponent(g)):c.push(this.encode(g,b+"["+("object"===typeof g?d:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)c.push(encodeURIComponent(b)+"="+encodeURIComponent(a));else for(d in a)Object.prototype.hasOwnProperty.call(a,
d)&&(b?c.push(this.encode(a[d],b+"["+d+"]")):c.push(this.encode(a[d],d)));return c.join("&")},decode:function(a){var d={},c=0,n={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var g=a[c].split("="),e=decodeURIComponent(g[0]),h=d,l=0,m=e.split("]["),k=m.length-1;/\[/.test(m[0])&&/\]$/.test(m[k])?(m[k]=m[k].replace(/\]$/,""),m=m.shift().split("[").concat(m),k=m.length-1):k=0;if(2===g.length)if(g=(g=decodeURIComponent(g[1]))&&!isNaN(g)?+g:g===b.Z?void 0:void 0!==
n[g]?n[g]:g,k)for(;l<=k;l+=1)e=""===m[l]?h.length:m[l],h=h[e]=l<k?h[e]||(m[l+1]&&isNaN(m[l+1])?{}:[]):g;else f.R(d[e])?d[e].push(g):d[e]=void 0!==d[e]?[d[e],g]:g;else e&&(d[e]=void 0)}return d}},u={wa:{},oa:function(a){var b=document.cookie||"",c=this.wa[a];c||(c=a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=new RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),this.wa[a]=c);return(a=b.match(c))&&decodeURIComponent(a[1])},V:function(a,b,c){var d="";c&&(d="; expires="+c.toGMTString());document.cookie=
a+"="+b+d+"; path=/"},tc:function(a){this.V(a,"",new Date(1982,5,13))}},q={current:{}},h={la:!1,info:f.v,error:f.log,a:function(){window[b.F]&&(this.la=!0,window[b.F][b.info]&&(this[b.info]=window[b.F][b.info]),window[b.F][b.error]&&(this[b.error]=window[b.F][b.error]))},reset:function(){this.la=!1;this[b.info]=f.v;this[b.info]=f.log},Pb:function(a){var d=document.createElement(b.$a);d.src=f.ma()+b.g+b.Ja+a.message;d.setAttribute(b.width,b.wb);document.body?document.body.appendChild(d):document.head.appendChild(d)},
Qb:function(a){a===b.info?(this[b.info]=f.log,this[b.error]=f.log):a===b.error?(this[b.info]=f.v,this[b.error]=f.log):(this[b.info]=f.v,this[b.error]=f.v)}},e={K:0,o:{x:0,y:0},P:!0,a:function(){function a(){e.P=document[g]?!1:!0}function b(){e.flush();window.removeEventListener("DOMContentLoaded",b,!1)}function c(){/loaded|interactive|complete/.test(document.readyState)&&(document.detachEvent("onreadystatechange",c),h&&(h=!1,e.flush()))}var e=this;e.K=0;this.ub(window,"mousemove",function(a){e.o=
{x:a.clientX,y:a.clientY}});if("undefined"!==typeof document.hidden){var g="hidden";var f="visibilitychange"}else"undefined"!==typeof document.mozHidden?(g="mozHidden",f="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(g="msHidden",f="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(g="webkitHidden",f="webkitvisibilitychange");"undefined"!==typeof document.addEventListener&&"undefined"!==typeof g&&document.addEventListener(f,a,!1);var h=!0;window.addEventListener?window.addEventListener("DOMContentLoaded",
b,!1):document.attachEvent&&document.attachEvent("onreadystatechange",c)},Ga:function(a,b){var c=document.createElement("iframe"),d=document.body;c.setAttribute("name","spr");c.src=a;c.setAttribute("height","1");c.setAttribute("width","1");c.setAttribute("visible","false");c.setAttribute("id","spr-iframe-"+b);c.style.display="none";d||(d=this.b("BODY")[0]);d||(d=this.b("HEAD")[0]);h.info(a);d.appendChild(c);return c},Qa:function(){for(var a=this.b("meta"),b=0;b<a.length;b+=1)if("og:url"===a[b].getAttribute("property"))return a[b].content;
return!1},Pa:function(){for(var a=this.b("link"),b=0;b<a.length;b+=1)if("canonical"===a[b].rel)return a[b].href;return!1},Ra:function(){for(var a=this.b("meta"),b=0;b<a.length;b+=1)if("twitter:url"===a[b].getAttribute("name"))return a[b].content;return!1},Sa:function(){return window.location.protocol+"//"+window.location.hostname+window.location.pathname},ia:function(){return this.Pa()||this.Qa()||this.Ra()||this.Sa()},na:function(){return document.referrer},ha:function(a){for(var b=this.b("meta"),
c=0;c<b.length;c+=1)if("og:title"===b[c].getAttribute("property")||"twitter:title"===b[c].getAttribute("name"))return b[c].content;return document.title||a||!1},Db:function(a){var b=document.body,c=this.b("BODY")[0],e=this.b("HEAD")[0];b&&b.contains(a)?b.removeChild(a):c&&c.contains(a)?c.removeChild(a):e&&e.contains(a)&&e.removeChild(a);return a},Ha:function(a){var b=this,c=document.createElement("script");c.type="text/javascript";c.setAttribute("async",!0);c.setAttribute("name","spr");c.setAttribute("id",
"spr-script");c.src=a;h.info(a);this.S(function(){setTimeout(function(){b.b("HEAD")[0].appendChild(c)},1)});return c},h:[],ready:/loaded|interactive|complete/.test(document.readyState),flush:function(){var a=this.h.shift();for(this.ready=!0;a;)a(),a=this.h.shift()},S:function(a){this.ready?(this.h.push(a),this.flush()):document.documentElement.doScroll?window.self===window.top?function(){if(!document.uniqueID&&document.expando)return this.h.push(a);try{document.documentElement.doScroll("left"),a()}catch(d){setTimeout(arguments.callee,
0)}}():this.h.push(a):this.h.push(a)},ub:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},tb:function(a,b,c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},I:function(){return(window.pageYOffset?window.pageYOffset:document.documentElement?document.documentElement.scrollTop:0)-this.K},b:function(a){var b=[],c=0,e;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(document.getElementById(a.substring(1)));
break;case ".":var g=document.getElementsByTagName("*");for(e=" "+a.substring(1)+" ";c<g.length;c+=1)a=(" "+g[c].className+" ").replace(/[\n\t\r]/g," "),-1<a.indexOf(e)&&b.push(g[c]);break;default:b=document.getElementsByTagName(a)}return b}},v={ba:function(a){var d;var c=f.J(a);c[b.L]&&(c[b.L]=f.O(c[b.L]));c[b.N]&&(c[b.N]=f.O(c[b.N]));c[b.Y]&&(c[b.Y]=f.O(c[b.Y]));c[b.s]&&typeof c[b.s]!==b.X&&(c[b.s]=c[b.s].toString());c[b.referrer]=""==c[b.A]?"":this.U(c[b.referrer]);c[b.A]=this.U(c[b.A]);c[b.va]=
c[b.va]||window.location.toString();c[b.uid]?c[b.uid]=c[b.uid]:(d=this.Za())&&(c[b.uid]=d);c[b.url]&&(c[b.url]=this.Hb(c[b.url]),a[b.url]=c[b.url]);return c},U:function(a){""!==a&&(a=a||e.na());return a},Za:function(){return u.oa(b.Da)},Hb:function(a){if(0===a.indexOf("http%253A")||0===a.indexOf("https%253A"))a=decodeURIComponent(a);if(0===a.indexOf("http%3")||0===a.indexOf("https%3"))a=decodeURIComponent(a);return a}},p={callbacks:{},M:"SPR",Nb:function(a){this.M=a},f:function(a,d,c,h,g){h=h||function(){};
g||(g="cb");var k="cb"+f.Gb(),n=this;c[g]=this.M+".API.callbacks."+k;g=f.ma();"file://"===g&&(g="http://");c[b.Zb]=b.version;c=t.encode(c);var l=e.Ha(g+a+d+"?"+c);n.callbacks[k]=function(a){setTimeout(function(){l.parentNode.removeChild(l)},0);h(a);try{delete n.callbacks[k]}catch(D){n.callbacks[k]=null}}}},w={Cc:!1,vc:!0,i:0,Ba:5E3,Xb:12E5,interval:null,reset:function(){e.K=e.I();window.clearInterval(this.interval)},track:function(a){var d=this,c;d.interval=setInterval(function(){e.P&&(d.i+=d.Ba);
d.Ca()&&(d.i=0);c=f.J(a);c[b.t]=d.i;c[b.e]=d.hb()?5E3:0;c[b.ya]=e.I();0===c[b.c]&&(c[b.c]=b.Aa);e.P&&!d.Ca()&&d.ac(c)&&0<c[b.e]&&(d.i=0,p.f(b.g,b.Wb,c));d.jb=e.o.x;d.kb=e.o.y;d.ib=e.I()},d.Ba)},hb:function(){return!0!==this.Va?this.Va=!0:this.jb!==e.o.x||this.kb!==e.o.y||this.ib!==e.I()?!0:!1},Ca:function(){return this.i>=this.Xb},ac:function(a){return a[b.url]&&a[b.c]}},k=f.T,y={G:[],data:{},response:null,options:null,Hc:!1,a:function(a,d){this.reset();this.options=d;this.response=a;var c=this;e.S(function(){c.height=
c.Wa();c.C||(c.C=function(){c.ca()});q.current[b.rb]?c.Eb():c.Ia()})},Ia:function(){typeof document.addEventListener!==b.Z?document.addEventListener("scroll",this.C,!1):window.attachEvent("onscroll",this.C);this.ca()},Eb:function(){typeof document.removeEventListener!==b.Z?document.removeEventListener("scroll",this.C,!1):window.detachEvent("onscroll",this.C)},ca:function(){var a=this.Ya()+Math.min(document.documentElement.clientHeight,window.innerHeight||0),b=0;a>=this.height?b=k[3]:b=a/this.height*
100;97<=b?this.B(k[3]):b>=k[2]?this.B(k[2]):b>=k[1]?this.B(k[1]):b>=k[0]&&this.B(k[0])},Wa:function(){if(q.current[b.ga])var a=q.current[b.ga];else{a=document.body;var d=document.documentElement;a=Math.max(a.scrollHeight,a.offsetHeight,d.clientHeight,d.scrollHeight,d.offsetHeight)}return a},Ya:function(){var a="CSS1Compat"===(document.compatMode||"");return void 0!==window.pageYOffset?window.pageYOffset:a?document.documentElement.scrollTop:document.body.scrollTop},B:function(a){this.data={};if(!f.contains(k,
a))h[b.error](b.ra);else if(!f.contains(this.G,a))if(this.Ob(a),this.response[b.Na])this.Mb();else h[b.info](b.Ib)},Ob:function(a){var d;for(d=0;d<k.length;d+=1){var c=k[d];a>=c&&!f.contains(this.G,c)&&(this.G.push(c),this.data[c]=!0,h[b.info](b.za+c))}},w:function(){return f.ta({event:"csd",sd:this.data},this.options)},Mb:function(){if(!this.response.error){var a=this.w();p.f(b.g,b.ka,a)}},reset:function(){this.G=[]}},A={ua:[{name:b.mb,$:b.nb,aa:b.ob,l:b.l},{name:b.xb,$:b.yb,aa:b.zb,l:b.l}],Fb:function(a,
b){return{url:b}},Ub:function(a,d){return function(c){c={event:b.ya,url:a.url,cid:a.id,pid:a.pid,sn:a.name,data:c};f.ta(c,d);p.f(b.g,b.ka,c)}},m:function(a,b){for(var c=this.ua,d,e=0;e<c.length;e+=1){d=c[e];var h=f.J(a);h.name=d.name;a[d.name]&&p.f(d.$,d.aa,this.Fb(d.name,h.url),this.Ub(h,b),d.l)}}},B={track:function(a){var d=this;0===a[b.c]&&(a[b.c]=b.Aa);p.f(b.g,b.ab,a,function(c){y.a(c,a);if(c.error)h[b.error](b.W+c.error.code+" - "+c.error.message);else c.uid&&d.Rb(c.uid),A.m(c,a)})},Rb:function(a){u.V(b.Da,
a,new Date(2042,5,13))}},x={uc:{},ea:{},a:function(){try{e.a();var a=window[b.Bb];u.oa(b.xa)?this.sa=!0:this.sa=!1;u.V(b.xa,b.vb,new Date(2042,5,13));this.m(a)}catch(d){e.S(function(){h.Pb(d)})}},m:function(a){q.current=a;this.ea=f.J(q.current);this.ea[b.r]=this.sa;if(a)if(h.a(a[b.qa]),a[b.url]=a[b.url]||e.ia(),a[b.title]||(a[b.title]=e.ha(a[b.url])),a[b.url]){w.reset();var d=v.ba(a);d[b.Ab]||(!1!==a[b.Cb]&&(B.track(d),w.track(d)),!1!==a[b.Oa]&&this.Ta(d))}else h[b.error](b.W+b.ja);else h[b.error]("Params not passed to collect")},
Ta:function(a){a[b.referrer]=a[b.referrer]||e.na();a[b.A]=v.U(a[b.A]);a[b.Ka]=(new Date).getTime();a=t.encode(a);this.fa&&e.Db(this.fa);this.fa=e.Ga(b.Tb+b.La+b.Ma+"?"+a,b.x)}},r=[b.c,b.jc,b.lb,b.s],C={create:function(a,b){return new z(a,b)},a:function(a,b){return this.create(a,b).a()}};return{Reach:{collect:function(a){x.m(a)}},QS:{decode:t.decode},debug:h,setLogLevel:function(a){h.Qb(a)},API:p,collect:function(a){x.m(a)},decode:t.decode,init:function(){x.a()},iframeCollect:function(){},stop:function(){w.reset()},
scrollDepthReached:function(a){y.B(a)},video:function(a){return C.a(a,p.M)}}}();window.SPR.init();
